// Shared theme class names used across App.jsx and SettingsModal.jsx
export const THEME_CLASSES = ['light', 'midnight', 'forest', 'sunset', 'ocean', 'lavender', 'hotpink', 'snes', 'colorblind'];

export const A11Y_CLASSES = ['dyslexic-mode', 'reduced-motion', 'high-contrast', 'large-text'];

export const STORAGE_KEYS = {
    ADDRESS_MODE: 'addressMode',
    CHANNEL_DISPLAY_MODE: 'channelDisplayMode',
    CHANNEL_HOOKUP_COLUMN_ORDER: 'channelHookup_columnOrder',
    CHANNEL_HOOKUP_VISIBLE_COLUMNS: 'channelHookup_visibleColumns',
    COMPACT_MODE: 'compactMode',
    CUSTOM_THEME: 'customTheme',
    DEFAULT_GRID_HEIGHT: 'defaultGridHeight',
    DETAIL_PANEL_LAST_WIDTH: 'detailPanelLastWidth',
    DETAIL_PANEL_WIDTH: 'detailPanelWidth',
    DISABLE_LANDING: 'disableLanding',
    DYSLEXIC_MODE: 'dyslexicMode',
    HANGING_SCHEDULE_COLUMN_ORDER: 'hangingSchedule_columnOrder',
    HANGING_SCHEDULE_VISIBLE_COLUMNS: 'hangingSchedule_visibleColumns',
    HIGH_CONTRAST: 'highContrast',
    INSTRUMENT_SCHEDULE_COLUMN_WIDTHS: 'instrumentSchedule_columnWidths',
    INSTRUMENT_SCHEDULE_SORT_DIRECTION: 'instrumentSchedule_sortDirection',
    INSTRUMENT_SCHEDULE_SORT_FIELD: 'instrumentSchedule_sortField',
    INSTRUMENT_SCHEDULE_VISIBLE_COLUMNS: 'instrumentSchedule_visibleColumns',
    LARGE_TEXT: 'largeText',
    MAGIC_SHEET_CONFIGS: 'magicSheetConfigs',
    MAGIC_SHEET_CANVAS_MODE: 'magicSheet_canvasMode',
    MAGIC_SHEET_COLLAPSED_GROUPS: 'magicSheet_collapsedGroups',
    MAGIC_SHEET_GROUP_BY: 'magicSheet_groupBy',
    MAGIC_SHEET_GROUP_ORDER: 'magicSheet_groupOrder',
    MAGIC_SHEET_HIDE_DUPLICATES: 'magicSheet_hideDuplicates',
    MAGIC_SHEET_MERGED_GROUPS: 'magicSheet_mergedGroups',
    MOBILE_REFRESH: 'mobileRefresh',
    REDUCED_MOTION: 'reducedMotion',
    REPORT_FOOTER: 'reportFooter',
    SHOW_ALL_FIXTURE_TYPES: 'showAllFixtureTypes',
    SHOW_DATE_IN_FOOTER: 'showDateInFooter',
    SHOW_PAGE_NUMBERS: 'showPageNumbers',
    SHOW_UNIVERSE1: 'showUniverse1',
    SHOW_XYZ: 'showXYZ',
    THEME: 'theme',
    UNIT_SYSTEM: 'unitSystem',
    UNIVERSE_SEPARATOR: 'universeSeparator',
    VENUE_ADDRESS: 'venueAddress',
    VENUE_CONTACT: 'venueContact',
    VENUE_NAME: 'venueName',
    VENUE_NOTES: 'venueNotes',
};
